<head>
	<link rel="stylesheet" href="css/bootstrap.css" />
	<style>
		em{color:red;}
	</style>
</head>



<h2> Elastic Search </h2>




<form action= "<?php echo $_SERVER['PHP_SELF']; ?>" method="GET" >
<div>

<?php
echo "<b>Enter the search term  </b>";
echo "<input type='text' id='searchTerm' name='searchTerm' />";
echo "<input type='submit' class='btn-success btn-small' style='margin-bottom: 10px;' 
        name='querySubmit' value='Result'>";

?>

</div>
</form>


<?php



if(isset($_GET["searchTerm"])&&isset($_GET["querySubmit"])){

	$queryParam=$_GET["searchTerm"];
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, "localhost:9200/iprc/cases/_search");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "\n{\n   \"query\": {\n      \"multi_match\": {\n         \"query\": \".$queryParam.\",\n         \"fields\": [\"details\",\"equipmentType\"]\n      }\n   },\n   \"highlight\": {\n       \n        \"fields\" : {\n            \"details\" : {},\n            \"possibleCause\":{}\n        }\n   },\n\"size\": 100\n}");
	curl_setopt($ch, CURLOPT_POST, 1);

	$headers = array();
	$headers[] = "Content-Type: application/x-www-form-urlencoded";
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close ($ch);
	
	$jj=json_decode($result);
	$arrRes=$jj->hits->hits;	
	// print_r($arrRes);
	$len=sizeof($arrRes);
	echo $len;

	$str="<table border='1'>";
	for($i=0;$i<$len;$i++)
	// foreach ($arrRes as $value) {
	// 	# code...
	// }
	{
		$source=$arrRes[$i]->_source;
		// print_r($arrRes[$i]->_source->id);
		// print_r($arrRes[$i]);
		$str.="<tr>";
		$str.="<td>".$source->id."</td>";
		// $str.="<td>".$temp->."</td>";
		$str.="<td>".$source->equipmentType."</td>";
		$str.="<td>".$arrRes[$i]->_score."</td>";
		$str.="<td>".implode("....",$arrRes[$i]->highlight->details)."</td>";
		
		
		$str.="</tr>";
		// echo "---------------";
		// echo "<hr/>";
	}
	$str.="<table>";
	echo $str;
	#print_r($str);
}

?>